//types contract
export const SET_VALUE_SUCCESS = "SET_VALUE_SUCCESS";
export const SET_VALUE_ERROR = "SET_VALUE_ERROR";
export const SET_VALUE_PENDING = "SET_VALUE_PENDING";
export const GET_VALUE_SUCCESS = "GET_VALUE_SUCCESS";
export const GET_VALUE_ERROR = "GET_VALUE_ERROR";
export const GET_VALUE_PENDING = "GET_VALUE_PENDING";

export const WRITE_MESSAGE_PENDING = "WRITE_MESSAGE_PENDING ";
export const WRITE_MESSAGE_SUCCESS = "WRITE_MESSAGE_SUCCESS";
export const WRITE_MESSAGE_ERROR = "WRITE_MESSAGE_ERROR";

export const READ_MESSAGE_PENDING = "READ_MESSAGE_PENDING";
export const READ_MESSAGE_SUCCESS = "READ_MESSAGE_SUCCESS";
export const READ_MESSAGE_ERROR = "READ_MESSAGE_ERROR";

export const LOG_EVENT = "LOG_EVENT";
export const DEPLOY = "DEPLOY";
