//types contract
export const SET_VALUE_SUCCESS = "SET_VALUE_SUCCESS";
export const GET_VALUE_SUCCESS = "GET_VALUE_SUCCESS";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";
export const TRANSACTION_PENDING = "TRANSACTION__PENDING";

export const LOG_EVENT = "LOG_EVENT";
export const DEPLOY = "DEPLOY";
